# For help please refer to http://bit.ly/oW6iR1 or http://bit.ly/rcN2QB
configuration:
  permissions: true
  messages: true
items:
- WOOD_PICKAXE
- STONE_PICKAXE
- IRON_PICKAXE
- GOLD_PICKAXE
- DIAMOND_PICKAXE