name: GlowstoneDrop
main: de.dustplanet.glowstonedrop.GlowstoneDrop
version: ${project.version}-b${BUILD_NUMBER}
author: xGhOsTkiLLeRx
authors: [XxFuNxX]
description: Get a glowstone block back!
website: http://bit.ly/oW6iR1
website: http://bit.ly/rcN2QB
commands:
  glowstonedrop:
    description: Handles all the GlowstoneDrop commands
    usage: /glowstonedrop help or /glowdrop help - to see the help
    aliases: [glowdrop]
permissions:
  glowstonedrop.*:
    description: Gives access to all GlowstoneDrop permissions
    children:
     glowstonedrop.reload: true
     glowstonedrop.use.*: true
     glowstonedrop.enable.*: true
     glowstonedrop.disable.*: true
     glowstonedrop.help: true
     glowstonedrop.set: true
  glowstonedrop.use.*:
    description: Gives access to all GlowstoneDrop uses
    default: op
  glowstonedrop.set:
    description: Gives access to all GlowstoneDrop set commands
    default: op
  glowstonedrop.help:
    description: Allows you to see the help
    default: op
  glowstonedrop.reload:
    description: Allows you to reload the config
    default: op
  glowstonedrop.enable.*:
    description: Gives access to all GlowstoneDrop enable commands
    children:
     glowstonedrop.enable.permissions: true
     glowstonedrop.enable.messages: true
  glowstonedrop.disable.*:
    description: Gives access to all GlowstoneDrop disable commands
    children:
     glowstonedrop.disable.permissions: true
     glowstonedrop.disable.messages: true
  glowstonedrop.enable.permissions:
    description: Allows you to enable permissions
    default: op
  glowstonedrop.disable.permissions:
    description: Allows you to disable permissions
    default: op
  glowstonedrop.enable.messages:
    description: Allows you to enable messages
    default: op
  glowstonedrop.disable.messages:
    description: Allows you to disable messages
    default: op